; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

; --- Global Shared Configurations ---
[env:esp32-c6-devkitc-1] 
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

; Force compiler to acknowledge 8MB Flash limits
; 1. Tell the compiler you have an 8MB flash chip
board_build.flash_size = 8MB
; 2. Tell the flasher (esptool.py) to write with 8MB parameters
board_upload.flash_size = 8MB
; 3. Overwrite the default 4MB firmware checker limit (8MB in bytes)
board_upload.maximum_size = 8388608
; 4. Use the framework's built-in 8MB layout, local file not needed.
board_build.partitions = default_8MB.csv
; 5. Makes PlatformIO bypass dynamic online registry checks, to rely on its verified, local
; cross-compilers instead, which should resolve dependency initialization failures.
board_build.arduino.upstream_packages = no

; Add your missing libraries here (one per line, indented)
lib_deps = 
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    mathieucarbou/AsyncTCP @ ^3.3.2
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
    Wire @ ^3.3.11

; --- Individual Board Environments ---
[env:board_00]
extends = env:esp32-c6-devkitc-1
upload_port = COM4
monitor_port = COM4
build_flags = 
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ESP32_HOSTNAME='"ESP32-00"'

[env:board_01]
extends = env:esp32-c6-devkitc-1
upload_port = COM5
monitor_port = COM5
build_flags = 
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ESP32_HOSTNAME='"esp32-01"'

[env:board_02]
extends = env:esp32-c6-devkitc-1
upload_port = COM6
monitor_port = COM6
build_flags = 
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ESP32_HOSTNAME='"esp32-02"'

[env:board_03]
extends = env:esp32-c6-devkitc-1
upload_port = COM7
monitor_port = COM7
build_flags = 
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ESP32_HOSTNAME='"esp32-03"'
